baseurl = "http://sarahallenreed.com"
title = "Sarah Allen Reed, Goblin Queen."
theme = "hugo-theme-nix"
languageCode = "en-us"

  [[menu.header]]
    name = "resume"
    weight = 1
    url = "/resume"
  [[menu.header]]
    name = "art"
    weight = 2
    url = "/art"
##  [[menu.header]]
##    name = "writings"
##    weight = 3
##    url = "/writings"
  [[menu.header]]
    name = "illustration"
    weight = 4
    url = "/illustration"
  [[menu.header]]
    name = "sequential"
    weight = 5
    url = "/sequential"
  [[menu.header]]
    name = "audio"
    weight = 6
    url = "/audio"
  [[menu.header]]
    name = "buystuff"
    weight = 7
    url = "/buystuff"
  [[menu.header]]
    name = "hireme"
    weight = 8
    url = "/hireme"
  [[menu.header]]
    name = "patreon"
    weight = 9
    url = "https://patreon.com/sarahallenreed/"
  [[menu.header]]
    name = "about"
    weight = 10
    url = "/about"
  [[menu.header]]
    name = "contact"
    weight = 11
    url = "/contact"


[params]
  nocomments = true
  About = "Cartoonist. Author. Musician. Diogenes's Daughter. Undisputed Queen of Goblins."
  InstagramID = "sarahallenreed"
  TwitterID = "sarahallenreed"
  BandcampID = "sarahallenreed"
  GithubID = "sarahallenreed"
##  SoundcloudID = "sarahallenreed"
## TwitchID = "sarahallenreed"
##  PatreonID = "sarahallenreed"
  Name = "Sarah Allen Reed"
  Email = "sketchreed@gmail.com"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
