baseurl = "http://sarahallenreed.com"
title = "Sarah Allen Reed, Goblin Queen."
theme = "hugo-theme-nix"
languageCode = "en-us"

  [[menu.header]]
    name = "resume"
    weight = 1
    url = "/resume"
  [[menu.header]]
    name = "art"
    weight = 2
    url = "/art"
  [[menu.header]]
    name = "illustration"
    weight = 3
    url = "/illustration"
  [[menu.header]]
    name = "sequential"
    weight = 4
    url = "/sequential"
  [[menu.header]]
    name = "music"
    weight = 5
    url = "/music"
###
###[[menu.header]]
### name = "buymystuff"
### weight = 6
### url = "/buymystuff"
###
  [[menu.header]]
    name = "hireme"
    weight = 7
    url = "/hireme"
  [[menu.header]]
    name = "blog"
    weight = 8
    url = "https://heymamasarah.neocities.org/"
  [[menu.header]]
    name = "about"
    weight = 9
    url = "/about"
  [[menu.header]]
    name = "contact"
    weight = 10
    url = "/contact"


[params]
  nocomments = true
  About = "Cartoonist. Author. Musician. Diogenes's Daughter. Undisputed Queen of Goblins."
  InstagramID = "sarahallenreed"
  TwitterID = "sarahallenreed"
  BandcampID = "sarahallenreed"
  GithubID = "sarahallenreed"
##  SoundcloudID = "sarahallenreed"
## TwitchID = "sarahallenreed"
##  PatreonID = "sarahallenreed"
  Name = "Sarah Allen Reed"
  Email = "sketchreed@gmail.com"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
