baseurl = "http://sarahallenreed.com"
title = "Sarah Allen Reed, Goblin Queen."
theme = "hugo-theme-nix"
languageCode = "en-us"

  [[menu.header]]
    name = "catalogue"
    weight = 1
    url = "/catalogue"
  [[menu.header]]
    name = "illustration"
    weight = 2
    url = "/illustration"
  [[menu.header]]
    name = "sequential"
    weight = 3
    url = "/sequential"
  [[menu.header]]
    name = "music"
    weight = 4
    url = "/music"
  [[menu.header]]
    name = "about"
    weight = 5
    url = "/about"
  [[menu.header]]
    name = "blog"
    weight = 6
    url = "/blog"
  [[menu.header]]
    name = "contact"
    weight = 7
    url = "/contact"


[params]
  nocomments = true
  About = "Cartoonist. Author. Musician. Diogenes's Daughter. Undisputed Queen of Goblins."
  InstagramID = "sarahallenreed"
  TwitterID = "sarahallenreed"
  BandcampID = "sarahallenreed"
  GithubID = "sarahallenreed"
##  SoundcloudID = "sarahallenreed"
## TwitchID = "sarahallenreed"
##  PatreonID = "sarahallenreed"
  Name = "Sarah Allen Reed"
  Email = "sketchreed@gmail.com"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
