baseurl = "http://sarahallenreed.com"
title = "Sarah Allen Reed, Goblin Queen."
theme = "hugo-theme-nix"
languageCode = "en-us"

[menu]

  [[menu.header]]
    identifier = "audio"
    name = "audio works"
    weight = 1
     [[menu.header]]
       parent = "audio"
       weight = 1
       name = "ophelia drowning"
       url = "https://opheliadrowning.bandcamp.com"
     [[menu.header]]
       parent = "audio"
       weight = 2
       name = "coma roulette"
       url = "https://comaroulette.bandcamp.com"
     [[menu.header]]
       parent = "audio"
       weight = 3
       name = "shibito"
       url = "https://shibito.bandcamp.com"
     [[menu.header]]
       parent = "audio"
       weight = 4
       name = "ex-"
       url = "https://ex-idm.bandcamp.com"
     [[menu.header]]
       parent = "audio"
       weight = 5
       name = "solo symphonic work"
       url = "https://sarahallenreed.bandcamp.com"
     [[menu.header]]
       parent = "audio"
       weight = 6
       name = "radio shows, other bands, and more"
       url = "/audio"

  [[menu.header]]
    identifier = "illustration"
    name = "art and illustration"
    weight = 3
    url = "/illustration"
     [[menu.header]]
       parent = "illustration"
       name = "full-color illustration"
       weight = 1
       url = "/illustration/fullcolor"
     [[menu.header]]
       parent = "illustration"
       name = "black and white illustration"
       weight = 2
       url = "/illustration/blackandwhite"
#     [[menu.header]]
#       parent = "illustration"
#       name = "poster design"
#       weight = 3
#       url = "/illustration/posterdesign"
     [[menu.header]]
       parent = "illustration"
       name = "logo design"
       weight = 4
       url = "/illustration/logodesign"
     [[menu.header]]
       parent = "illustration"
       name = "book layout samples"
       weight = 5
       url = "/illustration/booklayoutsamples/"
     [[menu.header]]
       parent = "illustration"
       name = "package design"
       weight = 6
       url = "/illustration/fullpackage"
#     [[menu.header]]
#       parent = "illustration"
#       name = "personal work and fine art"
#       weight = 7
#       url = "/illustration/personal"


  [[menu.header]]
    identifier = "comics"
    name = "sequential art samples"
    weight = 4
    url = "/comics"
     [[menu.header]]
       parent = "comics"
       name = "selected sequential art"
       url = "/comics/sampleart1"
     [[menu.header]]
       parent = "comics"
       name = "sample story: barren chapter 1"
       url = "/comics/samplestory1"
     [[menu.header]]
       parent = "comics"
       name = "sample story: i am beginning to empathize with bukowski"
       url = "/comics/samplestory2"
     [[menu.header]]
       parent = "comics"
       name = "sample story: the grizzly daily strips"
       url = "/comics/samplestory3"
#     [[menu.header]]
#       parent = "comics"
#       name = "sample story 4"
#       url = "/comics/samplestory4"
#     [[menu.header]]
#       parent = "comics"
#       name = "sample story 5"
#       url = "/comics/samplestory5"
#     [[menu.header]]
#       parent = "comics"
#       name = "sample story 6"
#       url = "/comics/samplestory6"

  [[menu.header]]
    weight = 5
    identifier = "resume"
    name = "resume, bio, and hiring info"
    url = "/resume"
     [[menu.header]]
       parent = "resume"
       weight = 1
       name = "who is sarah allen reed?"
       url = "/resume/bio"
    [[menu.header]]
       parent = "resume"
       weight = 2
       name = "bibliography and discography"
       url = "/resume/bibliography/"
    [[menu.header]]
      parent = "resume"
      weight = 3
      name = "past clients and peer reviews"
      url = "/resume/clientreview/"
    [[menu.header]]
      parent = "resume"
      weight = 4
      name = "rates, policies, and information"
      url = "/resume/hireme"

  [[menu.header]]
    identifier = "links"
    name = "patreon, shop, and more"
    weight = 6
     [[menu.header]]
       parent = "links"
       name = "patreon"
       url = "https://patreon.com/sarahallenreed"
     [[menu.header]]
       parent = "links"
       name = "merch"
       url = "https://shop.spreadshirt.com/sarahallenreed/"



[params]
  Name = "Sarah Allen Reed"
  Email = "sketchreed@gmail.com"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
  HeaderHostname = "sarahallenreed.com"
  About = "Cartoonist. Author. Musician. Undisputed Queen Of Goblins."
  InstagramID = "sarahallenreed"
  TwitterID = "sarahallenreed"
  BandcampID = "sarahallenreed"
  GithubID = "sarahallenreed"
  PatreonID = "sarahallenreed"
