# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "NeonNine"
license = "MIT"
licenselink = "https://github.com/sarahallenreed/hugo-theme-neonnine/blob/master/LICENSE.md"
description = "Dark theme for Hugo."
homepage = "https://github.com/sarahallenreed/hugo-theme-neonnine"
tags = ["simple", "minimal", "unix", "terminal", "blog"]
features = ["blog"]
min_version = 0.01

[author]
  name = "Sarah Allen Reed"
  homepage = "https://sarahallenreed.com"

